version: '3.3'
services:
 mongo:
  image: mongo:4.2.5
  restart: always
  ports:
    - '27017:27017'
 my_app:
  build: .
  environment:
    WAIT_HOSTS: mongo:27017
  ports:
    - '8080:8080'
 nginx:
  build: ./nginx
  ports:
    - '80:80'
    - '443:443'